// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://pbvmtuqwbyaarolomoid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidm10dXF3YnlhYXJvbG9tb2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MTYyMTAsImV4cCI6MjA4NjM5MjIxMH0.UzAOSTBvm9OyrbTPL8_tlub2ll3t0IaxPxSncEyIqLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
